export interface DBItem {
    id: number;
    title: string;
    description: string;
    url: string;
  }

  export const fakeDB: DBItem[] = [
    {
        id: 1,
        title: 'react js',
        description: 'React is a JavaScript library for building UIs',
        url: 'https://react.dev/',
      },
      {
        id: 2,
        title: 'react js tutorial',
        description: 'Tutorial for React.js',
        url: 'https://react.dev/learn',
      },
      {
        id: 3,
        title: 'react jsx',
        description: 'JSX in React',
        url: 'https://react.dev/learn/writing-markup-with-jsx',
      },
      {
        id: 4,
        title: 'react js documentation',
        description: 'Docs for React.js',
        url: 'https://react.dev/documentation',
      },
      {
        id: 5,
        title: 'react js interview questions',
        description: 'Common interview questions for React',
        url: 'https://example.com/react-interview',
      },
      {
        id: 6,
        title: 'react json schema form',
        description: 'Libraries for JSON schema forms in React',
        url: 'https://rjsf-team.github.io/react-jsonschema-form/',
      },
      {
        id: 7,
        title: 'react jwt',
        description: 'How to handle JWT in React apps',
        url: 'https://example.com/react-jwt',
      },
      {
        id: 8,
        title: 'react jss',
        description: 'CSS-in-JS library JSS for React',
        url: 'https://cssinjs.org/react-jss',
      },
      {
        id: 9,
        title: 'react jsx for loop',
        description: 'How to loop in JSX',
        url: 'https://example.com/react-jsx-loop',
      },
      {
        id: 10,
        title: 'react js hooks',
        description: 'Introduction to React Hooks',
        url: 'https://react.dev/learn',
      },
      {
        id: 11,
        title: 'react js state management',
        description: 'State management in React',
        url: 'https://react.dev/learn/state-management',
      },
      {
        id: 12,
        title: 'react js context api',
        description: 'Using Context API in React',
        url: 'https://react.dev/learn/context',
      },
      {
        id: 13,
        title: 'react js lifecycle methods',
        description: 'Lifecycle methods in React',
        url: 'https://react.dev/learn/lifecycle-methods',
      },
      {
        id: 14,
        title: 'react js functional components',
        description: 'Functional components in React',
        url: 'https://react.dev/learn/functional-components',
      },
      {
        id: 15,
        title: 'react js class components',
        description: 'Class components in React',
        url: 'https://react.dev/learn/class-components',
      },
      {
        id: 16,
        title: 'react js props',
        description: 'Using props in React',
        url: 'https://react.dev/learn/props',
      },
      {
        id: 17,
        title: 'react js state',
        description: 'Using state in React',
        url: 'https://react.dev/learn/state',
      },
      {
        id: 18,
        title: 'react js events',
        description: 'Handling events in React',
        url: 'https://react.dev/learn/events',
      },
      {
        id: 19,
        title: 'react js forms',
        description: 'Handling forms in React',
        url: 'https://react.dev/learn/forms',
      },
      {
        id: 20,
        title: 'react js refs',
        description: 'Using refs in React',
        url: 'https://react.dev/learn/refs',
      },
      {
        id: 21,
        title: 'react js fragments',
        description: 'Using fragments in React',
        url: 'https://react.dev/learn/fragments',
      },
      {
        id: 22,
        title: 'react js portals',
        description: 'Using portals in React',
        url: 'https://react.dev/learn/portals',
      },
      {
        id: 23,
        title: 'react js error boundaries',
        description: 'Using error boundaries in React',
        url: 'https://react.dev/learn/error-boundaries',
      },
      {
        id: 24,
        title: 'react js higher-order components',
        description: 'Using higher-order components in React',
        url: 'https://react.dev/learn/higher-order-components',
      },
      {
        id: 25,
        title: 'react js render props',
        description: 'Using render props in React',
        url: 'https://react.dev/learn/render-props',
      },
      {
        id: 26,
        title: 'react js code splitting',
        description: 'Code splitting in React',
        url: 'https://react.dev/learn/code-splitting',
      },
      {
        id: 27,
        title: 'react js lazy loading',
        description: 'Lazy loading in React',
        url: 'https://react.dev/learn/lazy-loading',
      },
      {
        id: 28,
        title: 'react js suspense',
        description: 'Using Suspense in React',
        url: 'https://react.dev/learn/suspense',
      },
      {
        id: 29,
        title: 'react js memo',
        description: 'Using memo in React',
        url: 'https://react.dev/learn/memo',
      },
      {
        id: 30,
        title: 'react js useMemo',
        description: 'Using useMemo in React',
        url: 'https://react.dev/learn/useMemo',
      },
      {
        id: 31,
        title: 'angular js',
        description: 'Angular is a platform for building mobile and desktop web applications.',
        url: 'https://angular.io/',
      },
      {
        id: 32,
        title: 'angular tutorial',
        description: 'Tutorial for Angular.',
        url: 'https://angular.io/start',
      },
      {
        id: 33,
        title: 'angular components',
        description: 'Components in Angular.',
        url: 'https://angular.io/guide/component-overview',
      },
      {
        id: 34,
        title: 'angular services',
        description: 'Services in Angular.',
        url: 'https://angular.io/guide/architecture-services',
      },
      {
        id: 35,
        title: 'angular directives',
        description: 'Directives in Angular.',
        url: 'https://angular.io/guide/built-in-directives',
      },
      {
        id: 36,
        title: 'angular forms',
        description: 'Handling forms in Angular.',
        url: 'https://angular.io/guide/forms-overview',
      },
      {
        id: 37,
        title: 'angular routing',
        description: 'Routing in Angular.',
        url: 'https://angular.io/guide/router',
      },
      {
        id: 38,
        title: 'angular http client',
        description: 'HTTP client in Angular.',
        url: 'https://angular.io/guide/http',
      },
      {
        id: 39,
        title: 'angular testing',
        description: 'Testing in Angular.',
        url: 'https://angular.io/guide/testing',
      },
      {
        id: 40,
        title: 'angular cli',
        description: 'Angular CLI.',
        url: 'https://angular.io/cli',
      },
      {
        id: 41,
        title: 'vue js',
        description: 'Vue.js is a progressive JavaScript framework.',
        url: 'https://vuejs.org/',
      },
      {
        id: 42,
        title: 'vue js tutorial',
        description: 'Tutorial for Vue.js.',
        url: 'https://vuejs.org/v2/guide/',
      },
      {
        id: 43,
        title: 'vue js components',
        description: 'Components in Vue.js.',
        url: 'https://vuejs.org/v2/guide/components.html',
      },
      {
        id: 44,
        title: 'vue js directives',
        description: 'Directives in Vue.js.',
        url: 'https://vuejs.org/v2/guide/custom-directive.html',
      },
      {
        id: 45,
        title: 'vue js forms',
        description: 'Handling forms in Vue.js.',
        url: 'https://vuejs.org/v2/guide/forms.html',
      },
      {
        id: 46,
        title: 'vue js routing',
        description: 'Routing in Vue.js.',
        url: 'https://router.vuejs.org/',
      },
      {
        id: 47,
        title: 'vue js state management',
        description: 'State management in Vue.js.',
        url: 'https://vuex.vuejs.org/',
      },
      {
        id: 48,
        title: 'vue js transitions',
        description: 'Transitions in Vue.js.',
        url: 'https://vuejs.org/v2/guide/transitions.html',
      },
      {
        id: 49,
        title: 'vue js mixins',
        description: 'Mixins in Vue.js.',
        url: 'https://vuejs.org/v2/guide/mixins.html',
      },
      {
        id: 50,
        title: 'vue js plugins',
        description: 'Plugins in Vue.js.',
        url: 'https://vuejs.org/v2/guide/plugins.html',
      },
      {
        id: 51,
        title: 'svelte js',
        description: 'Svelte is a radical new approach to building user interfaces.',
        url: 'https://svelte.dev/',
      },
      {
        id: 52,
        title: 'svelte tutorial',
        description: 'Tutorial for Svelte.',
        url: 'https://svelte.dev/tutorial',
      },
      {
        id: 53,
        title: 'svelte components',
        description: 'Components in Svelte.',
        url: 'https://svelte.dev/docs#component-format',
      },
      {
        id: 54,
        title: 'svelte stores',
        description: 'Stores in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-store',
      },
      {
        id: 55,
        title: 'svelte transitions',
        description: 'Transitions in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-transition',
      },
      {
        id: 56,
        title: 'svelte animations',
        description: 'Animations in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-animate',
      },
      {
        id: 57,
        title: 'svelte lifecycle',
        description: 'Lifecycle in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-lifecycle',
      },
      {
        id: 58,
        title: 'svelte actions',
        description: 'Actions in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-action',
      },
      {
        id: 59,
        title: 'svelte context',
        description: 'Context in Svelte.',
        url: 'https://svelte.dev/docs#run-time-svelte-setContext',
      },
      {
        id: 60,
        title: 'svelte slots',
        description: 'Slots in Svelte.',
        url: 'https://svelte.dev/docs#slot',
      },
      {
        id: 61,
        title: 'ember js',
        description: 'Ember.js is a framework for ambitious web developers.',
        url: 'https://emberjs.com/',
      },
      {
        id: 62,
        title: 'ember tutorial',
        description: 'Tutorial for Ember.js.',
        url: 'https://guides.emberjs.com/release/tutorial/quick-start/',
      },
      {
        id: 63,
        title: 'ember components',
        description: 'Components in Ember.js.',
        url: 'https://guides.emberjs.com/release/components/',
      },
      {
        id: 64,
        title: 'ember routing',
        description: 'Routing in Ember.js.',
        url: 'https://guides.emberjs.com/release/routing/',
      },
      {
        id: 65,
        title: 'ember services',
        description: 'Services in Ember.js.',
        url: 'https://guides.emberjs.com/release/services/',
      },
      {
        id: 66,
        title: 'ember data',
        description: 'Data management in Ember.js.',
        url: 'https://guides.emberjs.com/release/models/',
      },
      {
        id: 67,
        title: 'ember templates',
        description: 'Templates in Ember.js.',
        url: 'https://guides.emberjs.com/release/templates/handlebars-basics/',
      },
      {
        id: 68,
        title: 'ember testing',
        description: 'Testing in Ember.js.',
        url: 'https://guides.emberjs.com/release/testing/',
      },
      {
        id: 69,
        title: 'ember addons',
        description: 'Addons in Ember.js.',
        url: 'https://guides.emberjs.com/release/addons-and-dependencies/',
      },
      {
        id: 70,
        title: 'ember cli',
        description: 'Ember CLI.',
        url: 'https://cli.emberjs.com/release/',
      },
      {
        id: 71,
        title: 'backbone js',
        description: 'Backbone.js gives structure to web applications.',
        url: 'https://backbonejs.org/',
      },
      {
        id: 72,
        title: 'backbone tutorial',
        description: 'Tutorial for Backbone.js.',
        url: 'https://backbonejs.org/#Getting-started',
      },
      {
        id: 73,
        title: 'backbone models',
        description: 'Models in Backbone.js.',
        url: 'https://backbonejs.org/#Model',
      },
      {
        id: 74,
        title: 'backbone views',
        description: 'Views in Backbone.js.',
        url: 'https://backbonejs.org/#View',
      },
      {
        id: 75,
        title: 'backbone collections',
        description: 'Collections in Backbone.js.',
        url: 'https://backbonejs.org/#Collection',
      },
      {
        id: 76,
        title: 'backbone routers',
        description: 'Routers in Backbone.js.',
        url: 'https://backbonejs.org/#Router',
      },
      {
        id: 77,
        title: 'backbone events',
        description: 'Events in Backbone.js.',
        url: 'https://backbonejs.org/#Events',
      },
      {
        id: 78,
        title: 'backbone sync',
        description: 'Sync in Backbone.js.',
        url: 'https://backbonejs.org/#Sync',
      },
      {
        id: 79,
        title: 'backbone history',
        description: 'History in Backbone.js.',
        url: 'https://backbonejs.org/#History',
      },
      {
        id: 80,
        title: 'backbone local storage',
        description: 'Local storage in Backbone.js.',
        url: 'https://github.com/jeromegn/Backbone.localStorage',
      },
    ];